config/routes.rb
Fobth::Application.routes.draw do
  
  devise_for :admins
  devise_for :users, :controllers => {:omniauth_callbacks => "authentications"}
  devise_scope :user do
    get '/login'                 =>"devise/sessions#new"
    get '/logout'                =>"devise/sessions#destroy"
    get '/signup'                =>"devise/registrations#new"
  end

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "home/index"
  get "contact/index"

  resources :authentications
  resources :products, only: [:index,:show]
  resources :news, only: [:index,:show]
  resources :category, only: [] do
    resources :products, only: [:index] do
      get 'page/:page', :action => :index, :on => :collection
    end
  end

  root :to => "home#index"


  match "/search" => "products#search", via: [:get, :post]

  concern :commentable do
    resources :comments
  end

  resources :products, concerns: :commentable

  get 'authentications/facebook'
  post 'authentications/facebook'
  match 'users/auth/facebook/callback', to: 'authentications#facebook', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable
  
  def create
    @comment = Comment.build_from( @commentable, current_user.id, params[:comment][:body] )
    @comment.save
    # if have parent
    if params[:comment][:parent_id].try(:to_i) > 0
      @parent = Comment.find(params[:comment][:parent_id])
      @comment.move_to_child_of(@parent)
    end
    redirect_to product_path(@commentable)
  end

  protected

  def load_commentable
    @commentable = Product.find(params[:comment][:commentable_id])
  end


end

app/views/comments/_comment.html.erb
<li class="comment" data-id="<%= comment.try(:id) %>" data-username="<%= comment.try(:user).try(:email).split("@").first %>">
  <div class="comment-content">
      <a href="javascript:void(0)" class="comment-author-avatar author-3692" target="_blank">
          <%= image_tag( avatar_url(comment.user), :height => '32', :width => '32', :class => 'avatar avatar-30') %>
      </a>

      <div class="content-bd">
          <span class="comment-author-name">
              <a href="javascript:void(0)" target="_blank"><%= comment.try(:user).try(:email).split("@").first %></a>
              <em class="colon">:</em>
          </span>
          <span class="comment-words">
              <% if comment.try(:parent) %>
                <a href="javascript:void(0)"><%= "@#{comment.try(:parent).try(:user).try(:email).split("@").first}" %></a>
              <% end %>
              <%= comment.try(:body) %>
          </span>
          <% if current_user %>
            <a href="javascript:void(0)" class="comment-op J_Reply">Reply</a>
          <% end %>
      </div>
      <div class="comment-date"><%= comment.try(:created_at) %></div>
  </div>
  <div class="h-dotted-line"></div>
</li>

app/views/comments/_form.html.erb
<%= form_for(:comment, :url => product_comments_path(commentable.id), :html => { :class => "comment-form J_CommentForm" }) do |f| %>
  <div class="user-avatar">
    <%= image_tag( avatar_url(current_user), :height => '32', :width => '32', :class => 'avatar avatar-30') %>       
  </div>

  <div class="user-reply J_UserReply" style="display: none;">
    <em class="user-to-reply J_UserToReply" href="javascript:void(0)"></em>
    <a class="del-user J_DelUser sprites" href="javascript:void(0)" title="Cancel"></a>
  </div>

  <div class="user-input">
    <textarea id="comment_body" class="comment-input J_CommentInput" name="comment[body]" placeholder="Say something..." data-default="Say something..." data-reply="Reply"></textarea>
  </div>

  <div class="user-op">
    <input type="submit" class="submit-comment J_SubmitComment" value="submit" data-loading="Submiting">
  </div>
  <%=f.hidden_field :commentable_id, :value => @product.id %>
  <%=f.hidden_field :parent_id, :value => 0, :class => "J_ParentId" %>
<% end %>