config/routes.rb
Fobth::Application.routes.draw do
  
  devise_for :admins
  devise_for :users, :controllers => {:omniauth_callbacks => "authentications"}
  devise_scope :user do
    get '/login'                 =>"devise/sessions#new"
    get '/logout'                =>"devise/sessions#destroy"
    get '/signup'                =>"devise/registrations#new"
  end

  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "home/index"
  get "contact/index"

  resources :authentications
  resources :products, only: [:index,:show]
  resources :news, only: [:index,:show]
  resources :category, only: [] do
    resources :products, only: [:index] do
      get 'page/:page', :action => :index, :on => :collection
    end
  end

  root :to => "home#index"


  match "/search" => "products#search", via: [:get, :post]

  concern :commentable do
    resources :comments
  end

  resources :products, concerns: :commentable

  get 'authentications/facebook'
  post 'authentications/facebook'
  match 'users/auth/facebook/callback', to: 'authentications#facebook', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
end

app/views/common/_footer.html.erb
<!-- #footer -->
<div id="footer">

    <div class="footer-bd">

        <div class="col-up clearfix">

            <!-- .friend-links -->
            <div class="section friend-links">
                <h3 class="section-title">Friend Links</h3>
                <ul class="closed link-list" id="J_LinksWrapper">
                    <%= render :partial => "common/link", :collection => @links %>
                </ul>
<!--                 <a href="javascript:void(0)" id="J_MoreLink" class="more-link">MORE...</a>
 -->            </div>
            <!-- END .friend-links -->

            <!-- .hot-tags -->
            <div class="section hot-tags">
                <h3 class="section-title">Hot Products</h3>
                <div class="tag-list">
                    <% if !@hots.blank? %>
                      <% is_first = true %>
                      <% for hot in @hots %>
                        <% unless is_first %>
                            <i class="point sprites"></i>
                        <% end %>
                        <% is_first = false %>
                        <%= link_to "#{hot.name}", "#{hot.url}", :style => "font-size: 12px;" %>
                      <% end %>
                    <% else %>
                      
                    <% end %>
                </div>
                <div class="footer-search">
                    <%= render :partial => "common/search" %>
                </div>
            </div>
            <!-- END .hot-tags -->

        </div>

        <!-- footer-logo, copyright, ued-links -->
        <div class="col-down clearfix">

            <em class="copyright">
                Copyright &copy; 2014 Fobth. All rights reserved.
            </em>

            <span class="ued-links">
                <a href="https://www.facebook.com/nancychen1104" target="_blank" class="rss sprites"></a>
                <a href="https://twitter.com/nancychen1104" target="_blank" class="twitter sprites"></a>
                <a href="https://www.youtube.com/user/nancychen1104" target="_blank" class="weibo sprites"></a>
            </span>

        </div>
        <!-- END footer-logo, copyright, ued-links -->

    </div>

</div>
<!-- END #footer -->

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Setting.google_analytics_key %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/common/_link.html.erb
<li>
  <%= link_to "#{link.name}", "#{link.url}", :target => "_blank" %>
</li>

app/views/common/_login.html.erb
<div id="J_Login" class="login">

  <% if user_signed_in?%>
    <a href="/logout" class="logout-entry">
      <%= image_tag( avatar_url(current_user), :height => '32', :width => '32', :class => 'avatar avatar-30') %>
      <em>Out</em>
    </a>
  <% else %>
    <a href="javascript:void(0)" class="login-entry J_LoginEntry" title="Login">Login</a>

    <div class="form-wrapper J_FormWrapper" style="display: none;">

      <i class="arrow-refer sprites"></i>

      <form name="loginform" action="" method="post">
        <p class="col-extra">
          <a class="weibo-login" href="javascript:void(0);" title="Login with Facebook">
            Facebook
          </a>
          <!-- <em class="vertical-line">|</em>
          <a class="twitter-login" href="javascript:void(0);" title="Login with Twitter">
            <i class="weibo-white sprites"></i>Twitter
          </a>
          <em class="vertical-line">|</em>
          <a class="google-login" href="javascript:void(0);" title="Login with Google">
            <i class="weibo-white sprites"></i>Google
          </a> -->
        </p> 
      </form>

    </div>
  <% end %>

</div>

app/views/common/_menu.html.erb
<!-- .col-left -->
<div class="col-left">

  <!-- #nav -->
  <div id="J_Nav" class="nav">

    <a class="ued-logo" href="http://www.fobth.com/" target="_self">
        <%= image_tag("logo.png", :size => "220x99", :alt => "Fobth") %> 
    </a>

    <div class="nav-menu">
      <div id="J_NavLabel" class="nav-label">
          <span></span>
      </div>
      <ul id="menu-primary" class="menu">
        <%= left_menu(@categories) %>
      </ul>
    </div>

    <div class="nav-search">
      <%= render :partial => "common/search" %>
    </div>

  </div>
  <!-- END #nav -->
</div>
<!-- END .col-left -->

app/views/common/_news.html.erb
<a class="timeline-date" href="javascript:void(0)" target="_self"><%= news.news_date %></a>
<div class="post-8816 post type-post status-publish format-standard hentry category-frontend category-bowen category-lanlan" data-id="8816">

    <div class="timeline-line"></div>

    <h3 class="post-title">
        <a href=<%= "#{news_path(news)}" %> title=<%= "#{news.title}" %> target="_self"><%= news.title %></a>
    </h3>

    <div class="h-dotted-line"></div>

    <div class="post-excerpt">
        <p><%= strip_tags(news.content).truncate(250) %> &hellip; <a class="readmore" href=<%= "#{news_path(news)}" %>>More&gt;</a>
        </p>
    </div>
    <% if news.image? %>
      <a class="post-thumb" href=<%= "#{news_path(news)}" %> target="_self">
        <%= image_tag(news.image.url) %>
      </a>
    <% end %>

    <div class="post-extra">
        <span class="post-date"><%= news.created_at %></span>
    </div>

</div>

app/views/common/_page.html.erb
<div class="page-nav">
  <div class="pre-page page sprites">
    <%= link_to_previous_page(@products,"pre") if @products %>
  </div>
  <div class="next-page page sprites">
    <%= link_to_next_page(@products, "next") if @products %>
  </div>
</div>

app/views/common/_product.html.erb
<li class="post">
  <div class="post-snapshoot">
    <i class="slide-bg"></i>
    <a class="post-thumb" href=<%= "#{product_path(product)}" %> target="_self" rel="bookmark">
        <img width="280" height="150" data-ks-lazyload=<%= "#{product.image.url}" %> class="attachment-thumb-pc wp-post-image" alt="928-280x150" />
    </a>
  </div>
  <%= link_to "#{product.name}", product_path(product), :class => "post-title", :target => "_self", :title => "#{product.name}", :rel => "bookmark" %>
  <div class="post-extra">
    <span class="post-date"><%= l product.created_at , :format => :long %></span>
    <!-- <span class="post-op">
        <a href="javascript:void(0)" class="like sprites">18</a>
        <a href="#" class="comment sprites" title="《title》上的评论">7 </a>
    </span> -->
  </div>
</li>

app/views/common/_search.html.erb
 <!-- 搜索框 -->
<form method="get" id="search" action="/search">
    <input type="text" maxlength="30" name="q" id="J_Input" class="input sprites" placeholder="<%= params[:q] || 'search' %>" value="">
</form>
<!-- END 搜索框 -->

app/views/common/_slider_ad.html.erb
<!-- .slider-ad -->
<div class="slider-ad clearfix">
  <div id="J_Slider" class="slider">
    <div class="slider-pannels">
      <div class="slider-pannel">
        <a class="pannel-bd" href="<%= "#{@home.try(:slide_url)}" %>" target="_blank">
          <img class="pannel-img" width="580px" height="320px" src="<%= "#{@home.try(:image).try(:url)}"  %>"  />
          <span class="pannel-title"><i class="mask"></i>
              <em><%= @home.try(:slide_title)  %></em>
          </span>
        </a>
      </div>
    </div>
  </div>
  <div class="ad">
    <a href="<%= "#{@home.try(:photo_url)}" %>" target="_blank">
      <img width="280px" height="320px" src="<%= "#{@home.try(:photo).try(:url)}"  %>" />
    </a>
  </div>
</div>
<!-- END .slider-ad -->